REM Favorite : Fill,
REM REM Converted from a DRAW PRESET binary to a DRAW RECORDING script
REM Created On Tuesday, October, 15, 1996 by antoniom

WITHOBJECT "CorelDraw.Automation.7"
	.StartOfRecording 
	.SuppressPainting 
	.RecorderStorePreselectedObjects FALSE
	.RecorderSelectObjectByIndex TRUE, 1
	.ApplyTextureFill "", "Cotton 3C", "Cdr5:Cotton 3C"
	.ResumePainting 
	.EndOfRecording 
END WITHOBJECT
