REM Favorite : Fill,
REM REM Converted from a DRAW PRESET binary to a DRAW RECORDING script
REM Created On Monday, October, 07, 1996 by doncl

WITHOBJECT "CorelDraw.Automation.7"
	.StartOfRecording 
	.SuppressPainting 
	.RecorderStorePreselectedObjects FALSE
	.RecorderSelectObjectByIndex TRUE, 1
	.ApplyTextureFill "", "Pottery Wheel 2 Colors", "Cdr5:Pottery Wheel 2 Colors"
	.ResumePainting 
	.EndOfRecording 
END WITHOBJECT
