REM Favorite : Fill,
REM REM Converted from a DRAW PRESET binary to a DRAW RECORDING script
REM Created On Sunday, October, 06, 1996 by doncl

WITHOBJECT "CorelDraw.Automation.7"
	.StartOfRecording 
	.SuppressPainting 
	.RecorderStorePreselectedObjects FALSE
	.RecorderSelectObjectByIndex TRUE, 1
	.ApplyTextureFill "", "Rain Drops Soft 2C", "Cdr5:Rain Drops Soft 2C"
	.ResumePainting 
	.EndOfRecording 
END WITHOBJECT
