REM Favorite : Fill,
REM REM Converted from a DRAW PRESET binary to a DRAW RECORDING script
REM Created On Tuesday, October, 15, 1996 by antoniom

WITHOBJECT "CorelDraw.Automation.7"
	.StartOfRecording 
	.SuppressPainting 
	.RecorderStorePreselectedObjects FALSE
	.RecorderSelectObjectByIndex TRUE, 1
	.ApplyFullColorFill "bars.cmx", 254000, 254000, 0, 0, TRUE, 0, FALSE, FALSE, 635000, 0, -444500, 190500
	.ResumePainting 
	.EndOfRecording 
END WITHOBJECT
