REM Favorite : Fill,
REM REM Converted from a DRAW PRESET binary to a DRAW RECORDING script
REM Created On Tuesday, October, 15, 1996 by antoniom

WITHOBJECT "CorelDraw.Automation.7"
	.StartOfRecording 
	.SuppressPainting 
	.RecorderStorePreselectedObjects FALSE
	.RecorderSelectObjectByIndex TRUE, 1
	.ApplyFountainFill 0, 0, 0, 1350, 256, 0, 0, 50
	.SetFountainFillColor 0, 5, 152, 46, 200, 0
	.SetFountainFillColor 100, 5, 255, 0, 0, 0
	.ResumePainting 
	.EndOfRecording 
END WITHOBJECT
