REM Favorite : Fill,
REM REM Converted from a DRAW PRESET binary to a DRAW RECORDING script
REM Created On Sunday, October, 06, 1996 by doncl

WITHOBJECT "CorelDraw.Automation.7"
	.StartOfRecording 
	.SuppressPainting 
	.RecorderStorePreselectedObjects FALSE
	.RecorderSelectObjectByIndex TRUE, 1
	.ApplyFountainFill 0, 0, 0, 900, 256, 0, 0, 50
	.SetFountainFillColor 0, 5, 253, 125, 13, 0
	.SetFountainFillColor 100, 5, 255, 255, 0, 0
	.ResumePainting 
	.EndOfRecording 
END WITHOBJECT
