REM Favorite : Fill,
REM REM Converted from a DRAW PRESET binary to a DRAW RECORDING script
REM Created On Tuesday, October, 15, 1996 by antoniom

WITHOBJECT "CorelDraw.Automation.7"
	.StartOfRecording 
	.SuppressPainting 
	.RecorderStorePreselectedObjects FALSE
	.RecorderSelectObjectByIndex TRUE, 1
	.ApplyFountainFill 3, -20, 17, 1345, 256, 33, 0, 50
	.SetFountainFillColor 0, 2, 0, 0, 0, 100
	.SetFountainFillColor 100, 2, 0, 0, 0, 0
	.ResumePainting 
	.EndOfRecording 
END WITHOBJECT
