REM Favorite : Fill,
REM REM Converted from a DRAW PRESET binary to a DRAW RECORDING script
REM Created On Sunday, October, 06, 1996 by doncl

WITHOBJECT "CorelDraw.Automation.7"
	.StartOfRecording 
	.SuppressPainting 
	.RecorderStorePreselectedObjects FALSE
	.RecorderSelectObjectByIndex TRUE, 1
	.ApplyFullColorFill "burst1.udi", 254000, 254000, 0, 0, TRUE, 0, FALSE, FALSE, 0, 0, 0, 0
	.ResumePainting 
	.EndOfRecording 
END WITHOBJECT
